/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 bot.gltf 
Author: Robin Butler (https://sketchfab.com/StarTrekGuy)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/robobit-dex-3b5d15acb0de42f685d71686c651dcd8
Title: RoboBit - Dex
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Bot(props) {
  const { nodes, materials } = useGLTF('/bot.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.717}>
        <mesh geometry={nodes.Sphere_0.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Sphere_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Sphere_2.geometry} material={materials['Material.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/bot.gltf')
